version: '3.5'

## Networking
###############################################################################

# Volumes
##############################################################################

## Services
###############################################################################
services:
    php:
        build:
            context: ./docker/php
            args:
                useruid: ${UID}
                username: app
            dockerfile: Dockerfile
        depends_on:
            - redis
        logging:
            driver: "json-file"
            options:
                max-size: "10000k"
        environment:
            DEBUG: ${DEBUG}
        working_dir: "/var/www/app/"
        user: app
        hostname: "tester"
        volumes:
            - "./:/var/www/app/"
            # Кеш и всё всё всё для композитора
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            # Конфигурация php
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini:ro"
    mariadb:
        build:
            context: ./docker/mysql
        shm_size: '300m'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_DATABASE: dbname
            MYDATA: "/dev/shm/data"
    redis:
        image: redis:3.2
    rabbit:
        image: rabbitmq:3.6-management
