version: '3.5'

## Networking
###############################################################################

# Volumes
##############################################################################
volumes:
    cache_vol:
        driver_opts:
          type: tmpfs
          device: tmpfs
## Services
###############################################################################
services:
    php:
        build:
            context: ./docker/php
            args:
                useruid: ${UID}
                username: app
            dockerfile: Dockerfile
        depends_on:
            - redis
        logging:
            driver: "json-file"
            options:
                max-size: "10000k"
        working_dir: "/var/www/app/"
#        user: app
        hostname: "tester"
        volumes:
            - "./:/var/www/app/"
            - "cache_vol:/var/www/app/var/cache"
            # Кеш и всё всё всё для композитора
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            # Конфигурация php
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini:ro"
    postgres:
        build:
            context: ./docker/postgres
        shm_size: '300m'
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: docker
            POSTGRES_DB: "database_name_docker.test"
            PGDATA: "/dev/shm/data"
        command: "postgres -c 'config_file=/etc/postgresql/postgresql.conf'"
        volumes:
            - "./docker/postgres/postgres.test.conf:/etc/postgresql/postgresql.conf"            
    redis:
        image: redis:3.2
