version: '3.5'

## Networking
###############################################################################

# Volumes
##############################################################################
volumes:
    cache_vol:
        driver_opts:
          type: tmpfs
          device: tmpfs
## Services
###############################################################################
services:
    php:
        build:
            context: ./docker/php
            args:
                useruid: ${UID}
                username: app
            dockerfile: Dockerfile
        depends_on:
            - redis
        logging:
            driver: "json-file"
            options:
                max-size: "10000k"
        working_dir: "/var/www/app/"
#        user: app
        hostname: "tester"
        volumes:
            - "./:/var/www/app/"
            - "cache_vol:/var/www/app/var/cache"
            # Кеш и всё всё всё для композитора
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            # Конфигурация php
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini:ro"
    redis:
        image: redis:3.2
