version: '3'

## Networking
###############################################################################

# Volumes
##############################################################################

## Services
###############################################################################
services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                useruid: ${UID}
                username: app
        logging:
            driver: "json-file"
            options:
                max-size: "10000k"
        environment:
            DEBUG: 1
            ENABLE_SSH: 1
        working_dir: "/var/www/app/"
        user: app
        hostname: "tester"
#        entrypoint: /home/app/docker-php-entrypoint
        volumes:
            # Директория с проектом
            - "./:/var/www/app/"
            # Кеш и всё всё всё для композитора
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            # Конфигурация php
            - "./docker/php/php.ini:/usr/local/etc/php/php.ini:ro"
            - "./docker/php/fpm_pool.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro"
            - "./docker/php/logs/:/var/logs/"
            # Директория для временной папки
            - "./docker/php/tmp:/tmp"
            # Конфигурация для гит
            - "${HOME}/.gitconfig:/home/app/.gitconfig:ro"
            # Секретные ключи ssh
            - "${SSH_KEY_PATH}:/home/app/.ssh"
            - "./docker/php/tmp.sh:/home/app/run.sh"
        ports:
            - "${EXTERNAL_SSH_PORT}:22"
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
                username: app
                useruid: ${UID}
        ports:
            - "${NGINX_EXTERNAL_PORT}:80"
            # Для статуса сервера
            - "${NGINX_STATUS_PORT}:8082"
        volumes:
            - ".:/var/www/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./docker/nginx/logs:/var/log/nginx"
        links:
            - php
    redis:
        image: redis:3.2
        ports:
            - "${REDIS_PORT}:6379"
